### ISSUE TITLE
Sending help for unrelated commands

### ISSUE THREAD

**Issue by mentonin** [minibradford88/Dungeon-World-Discord-Bot#1]
When using the help commands, the bot 
specifically, he sent me the help for `!shift`, `!volley`, `!defend`, `!parley`, `!trailblazer`, `!scout` `!quartermaster`, `!carouse`, in that order, after the correct answer to my command. First time happened on a call to `?newcharacter` and the second time happened on a call to `?shift`

**Comment by minibradford88** [comment]
Thanks for letting me know! I’m trying to replicate the error but it’s working fine for me. The only thing I can think of is sometimes the discord server is laggy and messages will stack up and then all respond at once.

Could you send me screenshots of the chat where this happened? This is my first debugging and it would help to see the issue.

Thanks!

**Comment by minibradford88** [comment]
Thanks for the tip, this issue was resolved by removing the possibility for empty messages when the user just types ?
